var a=prompt("enter the value of a");
a=parseInt(a);
var b=prompt("enter the value of b");
b=parseInt(b);
var temp;
var temp=a;
var a=b;
var b=temp;
alert("before swap"+"\n"+"value of a is"+a+"\n"+"value of b is"+b);
alert("after swap"+"\n"+"value of b is"+b+"\n"+"value of a is"+a);